TelaCadastro/Controllers/AlunoCidadeController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using DAL.Model;
using DAL.Persistence;
using TelaCadastro.Models;
using TelaCadastro.Util;
using TelaCadastro.ViewModels;

namespace TelaCadastro.Controllers
{
    public class AlunoCidadeController : Controller
    {
        public ActionResult Index()
        {
            var listaCidade = new CidadeDal().ObterTodos().ToList();
            var quantidade = listaCidade.Count();

            var paginacao = 5;

            var grid = new TabelaGenerica<Cidade>
            {
                Dados = listaCidade.ToList<Cidade>().OrderBy(ent => ent.nome).
                Take(paginacao > quantidade ? quantidade : paginacao).ToList(),
                Paginacao = paginacao,
                ClassesCss = "table table-hover",
                PaginaAtual = 1,
                TotalRegistros = quantidade
            };

            return View(grid);
        }

        public ActionResult TabelaCidade(Filtro[] filtros)
        {
            var paginacao = 5;
            var paginaAtual = 1;

            var listacidade = new CidadeDal().ObterTodos().ToList();

            if (filtros != null)
            {
                var listaFiltrosValidos = filtros.ToList<Filtro>().Where(ent => !String.IsNullOrEmpty(ent.value));
                foreach (var filtro in listaFiltrosValidos)
                {
                    switch (filtro.name)
                    {
                        case "codigo":
                            var id = Convert.ToInt32(filtro.value);
                            listacidade = listacidade.Where(ent => ent.cidadeid == id).ToList();
                            break;
                        case "nome":
                            listacidade = listacidade.Where(ent => ent.nome.Contains(filtro.value)).ToList();
                            break;
                        case "cep":
                            var cep = RemoveMascara(filtro.value);
                            listacidade = listacidade.Where(ent => ent.cep.Contains(cep)).ToList();
                            break;
                        case "estado":
                            listacidade = listacidade.Where(ent => ent.estado.Contains(filtro.value)).ToList();
                            break;
                        case "Paginacao":
                            paginacao = StrToInt32(filtro.value);
                            break;
                        case "PaginaAtual":
                            paginaAtual = StrToInt32(filtro.value);
                            break;
                    }
                }
            }

            int quantidade = listacidade.Count();

            var grid = new TabelaGenerica<Cidade>
            {
                Dados = listacidade.OrderBy(ent => ent.nome)
              .ToList()
              .Skip(paginacao * (paginaAtual - 1)).Take(paginacao > quantidade ? quantidade : paginacao).ToList(),
                Paginacao = paginacao,
                ClassesCss = "table table-hover",
                PaginaAtual = paginaAtual,
                TotalRegistros = quantidade
            };

            return View(grid);
        }

        public ActionResult Ordenar(string campo, string ordem)
        {

            var listacidade = new CidadeDal().ObterTodos().ToList();

            if (ordem == "cres")
            {
                switch (campo)
                {
                    case "cidadeid":
                        listacidade = listacidade.OrderBy(ent => ent.cidadeid).ToList();
                        break;
                    case "nome":
                        listacidade = listacidade.OrderBy(ent => ent.nome).ToList();
                        break;
                    case "estado":
                        listacidade = listacidade.OrderBy(ent => ent.estado).ToList();
                        break;
                    case "cep":
                        listacidade = listacidade.OrderBy(ent => ent.cep).ToList();
                        break;
                }

            }
            else
            {
                switch (campo)
                {
                    case "cidadeid":
                        listacidade = listacidade.OrderByDescending(ent => ent.cidadeid).ToList();
                        break;
                    case "nome":
                        listacidade = listacidade.OrderByDescending(ent => ent.nome).ToList();
                        break;
                    case "estado":
                        listacidade = listacidade.OrderByDescending(ent => ent.estado).ToList();
                        break;
                    case "cep":
                        listacidade = listacidade.OrderByDescending(ent => ent.cep).ToList();
                        break;
                }
            }

            var paginacao = StrToInt32(ConfigurationManager.AppSettings["PaginacaoPadrao"]);
            var paginaAtual = 1;

            int quantidade = listacidade.Count();

            var grid = new TabelaGenerica<Cidade>
            {
                Dados = listacidade.ToList()
              .Skip(paginacao * (paginaAtual - 1)).Take(paginacao > quantidade ? quantidade : paginacao).ToList(),
                Paginacao = paginacao,
                PaginaAtual = paginaAtual,
                TotalRegistros = quantidade
            };

            return View("TabelaCidade", grid);
        }

        public ActionResult BuscarAlunos(int id)
        {

            var paginacao = StrToInt32(ConfigurationManager.AppSettings["PaginacaoPadrao"]);
            var paginaAtual = 1;

            var listaaluno = new AlunoDal().ObterVarios(ent => ent.endereco.cidadeid == id);

            int quantidade = listaaluno.Count();

            var grid = new TabelaGenerica<Aluno>
            {
                Dados = listaaluno.OrderBy(ent => ent.nome)
              .ToList()
              .Skip(paginacao * (paginaAtual - 1)).Take(paginacao > quantidade ? quantidade : paginacao).ToList(),
                Paginacao = paginacao,
                ClassesCss = "table table-hover",
                PaginaAtual = paginaAtual,
                TotalRegistros = quantidade
            };

            return View("TabelaAluno", grid);
        }

        public int StrToInt32(string valor)
        {
            if (String.IsNullOrWhiteSpace(valor))
            {
                return 0;
            }
            else
            {
                return Convert.ToInt32(valor);
            }
        }

        public string RemoveMascara(string texto)
        {
            return texto == null ? null : (Regex.Replace(texto, "[?\\)?\\(_./-]", "")).Replace(" ", "");
        }
    }
}

TelaCadastro/Views/AlunoCidade/Index.cshtml
@model TelaCadastro.Util.TabelaGenerica<DAL.Model.Cidade>
@{
    ViewBag.Title = "Alunos de Cidades";
}

<div class="container">
    <div class="painel">
        <h4>Filtros</h4>
        <hr />

        @using (Html.BeginForm("TabelaCidade", "AlunoCidade", FormMethod.Get, new { id = "formFiltros" }))
        {
            @Html.Hidden("PaginaAtual")
            @Html.Hidden("Paginacao")

            <div class="row">
                <div class="grid-2">
                    @Html.Label("codigo", "Código")
                    @Html.TextBox("codigo", null, new { @class = "formulario-controle", @type = "Number" })
                </div>
                <div class="grid-4">
                    @Html.Label("nome", "Nome")
                    @Html.TextBox("nome", null, new { @class = "formulario-controle" })
                </div>
                <div class="grid-2">
                    @Html.Label("estado", "Estado")
                    @Html.TextBox("estado", null, new { @class = "formulario-controle" })
                </div>
                <div class="grid-2">
                    @Html.Label("cep", "CEP")
                    @Html.TextBox("cep", null, new { @class = "formulario-controle" })
                </div>
            </div>
            <br />
            <div class="row">
                <div class="grid-12">
                    <button type="button" class="botao botao-primario" onclick="filtrarGrid(null, 'alunocidade');">
                        Filtrar
                    </button>
                    <button type="button" class="botao botao-perigo" onclick="limparFiltros(null, 'alunocidade');">
                        Limpar
                    </button>
                </div>
            </div>
        }
    </div>
</div>

<br />

<div class="container">
    <div class="painel">
        <div class="row">
            <div id="divTabela">
                @Html.Partial("TabelaCidade", Model)
            </div>
        </div>
    </div>
</div>

<div class="abrir-modal" id="divTabelaAluno" style="display:none;">

</div>

@section Scripts{

    <script>
        $(document).ready(function () {
            $("#cep").mask("999.99-999");
        });

        function filtrarGrid(idForm, nomePagina, funcaoPosEvento, divTabela) {
            if (!verificaValor(idForm)) {
                idForm = "formFiltros";
            }

            if (!verificaValor(divTabela)) {
                divTabela = "divTabela";
            }

            $.post($("form[id=" + idForm + "] ").attr("action"), { filtros: $("form[id=" + idForm + "] ").serializeArray() })
                .done(function (data) {
                    $("#" + divTabela).html(data);

                    eval(funcaoPosEvento);

                    $('button[title]').qtip({
                        style: {
                            classes: "qtip-tipsy qtip-shadow qtip-rounded"
                        },
                        position: {
                            my: 'right top'
                        }
                    });
                    if (verificaValor(nomePagina)) {
                        $("form[id=" + idForm + "] input, select, textarea").each(function () {
                            if (verificaValor(localStorage[nomePagina + this.id])) {
                                localStorage.removeItem(nomePagina + this.id);
                            }
                        });
                        $("form[id=" + idForm + "] input, select, textarea").each(function () {
                            if (verificaValor(this.value)) {
                                localStorage.setItem(nomePagina + this.id, this.value);
                            }
                        });
                    }
                });
        }

        function limparFiltros(idForm, nomePagina, funcaoPosEvento, divTabela) {
            limparForm(idForm, nomePagina);
            filtrarGrid(idForm, nomePagina, funcaoPosEvento, divTabela);
        }

        function limparForm(idForm, nomePagina) {
            //Se não informou id, é para limpar outro form
            if (!verificaValor(idForm)) {
                idForm = "formFiltros";
            }

            //limpando todos os textbox's e hidden's
            $("form[id=" + idForm + "] textarea, form[id=" + idForm + "] input[type=number], form[id=" + idForm + "] input[type=text], form[id=" + idForm + "] input[type=hidden], form[id=" + idForm + "] input[type=date], form[id=" + idForm + "] select").val('');

            //limpando os radio's
            $("form[id=" + idForm + "] input[type=radio], form[id=" + idForm + "] input[type=checkbox]").each(function () {
                $(this).removeAttr('checked');
            });


            $("form[id=" + idForm + "] select").each(function () {
                $(this).val('');
                //$(this).selectpicker('refresh');

                $(this).val('').trigger("change");
            });

            if (verificaValor(nomePagina)) {
                //Limpando localStorage
                $("form[id=" + idForm + "] input, select, textarea").each(function () {
                    if (verificaValor(localStorage[nomePagina + this.id])) {
                        localStorage.removeItem(nomePagina + this.id);
                    }
                });
            }
        }

        function verificaValor(valor) {
            return valor != "" && valor != null && valor != undefined && valor != "undefined";
        }

        function BuscarAlunos(id) {
            $.post("AlunoCidade/BuscarAlunos", { id: id })
                .done(function (data) {
                    $("#divTabelaAluno").html(data);
                    $("#divTabelaAluno").show();
                });
        }

        function Ordenar(campo) {

            var ordem = "desc";
            var ultimocampo = localStorage.getItem("Ordenar");
            var ultimaordem = localStorage.getItem("Ordem");

            if (ultimocampo == campo) {
                if (ultimaordem == "cres")
                    ordem = "desc";
                else
                    ordem = "cres"
            }

            localStorage.setItem("Ordenar", campo);
            localStorage.setItem("Ordem", ordem);

            $.post("AlunoCidade/Ordenar", { campo: campo, ordem: ordem }).done(function (data) {
                $("#divTabela").html(data);
            });
        }

        function mudarPagina(pagina) {
            if (verificaValor(pagina)) {
                $("#PaginaAtual").val(pagina);
            }
            filtrarGrid();
        }

        function FecharModal() {
            $("#divTabelaAluno").hide();
        }

    </script>
}

TelaCadastro/Views/AlunoCidade/TabelaAluno.cshtml
@model TelaCadastro.Util.TabelaGenerica<DAL.Model.Aluno>
@{ Layout = null;
    int cont = (Model.PaginaAtual - 1) * Model.Paginacao; }
<div class="container">
    <div class="painel modal-painel">
        <button class="modal-fechar" onclick="FecharModal()">X</button>
        <h2>Alunos</h2>
        <hr />

        <div class="row">
            <table>
                <thead class="tableHead">
                    <tr>
                        <th>#</th>
                        <th>Código</th>
                        <th>Nome</th>
                        <th>Cpf</th>
                        <th>Sexo</th>
                        <th>Telefone</th>
                        <th>Data de Cadastro</th>
                        <th>Cidade</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody class="tableBody">
                    @foreach (var item in Model.Dados.OrderBy(ent => ent.nome))
                    {
        <tr>
            <td>@(cont = cont + 1)</td>
            <td>@item.alunoid</td>
            <td>@item.nome</td>
            <td>@item.cpf</td>
            <td>@(item.sexo == "M" ? "Masculino" : item.sexo == "F" ? "Feminino" : "")</td>
            <td>@item.telefone</td>
            <td>@(item.datacadastro.HasValue ? item.datacadastro.Value.ToShortDateString() : "")</td>
            <td>@item.endereco.cidade.nome</td>
        </tr>}
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="10">
                            <div class="col-md-4 col-sm-4 col-xs-4 pull-left">
                                @Html.HiddenFor(ent => ent.Paginacao)
                                <span class="link @(Model.Paginacao == 10 ? "link_selecionado" : "")" onclick="mudarPaginacao(10)">10</span>&nbsp;
                            </div>
                            <div class="col-md-4 col-sm-4 col-xs-4" style="text-align: center;">
                                <div class="form-inline input-group-sm">
                                    <button type="button" class="botao botao-primario" onclick="mudarPagina(@(Model.PaginaAtual == 1 ? 1 : Model.PaginaAtual - 1))"><span class="fa fa-chevron-left"></span></button>
                                    Página @Html.TextBoxFor(ent => ent.PaginaAtual, new { @class = "form-control", @style = "width: 35px;", @onkeyup = "mudarPagina();" }) de @Model.TotalPaginas &nbsp;
                                    <button type="button" class="botao botao-primario" onclick="mudarPagina(@(Model.PaginaAtual == Model.TotalPaginas ? Model.TotalPaginas : Model.PaginaAtual + 1))"><span class="fa fa-chevron-right"></span></button>
                                </div>
                            </div>
                            <div class="col-md-4 pull-right col-sm-4 col-xs-4" style="text-align: right">
                                <b>Total:</b> @Model.TotalRegistros
                            </div>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

TelaCadastro/Views/AlunoCidade/TabelaCidade.cshtml
@model TelaCadastro.Util.TabelaGenerica<DAL.Model.Cidade>
@{
    Layout = null;
    int cont = (Model.PaginaAtual - 1) * Model.Paginacao;
}
<table>
    <thead class="tableHead">
        <tr>
            <th>#</th>
            <th onclick="Ordenar('cidadeid')">Código</th>
            <th onclick="Ordenar('nome')" )>Nome</th>
            <th onclick="Ordenar('estado')">Estado</th>
            <th onclick="Ordenar('cep')">Cep</th>
            <th></th>
        </tr>
    </thead>
    <tbody class="tableBody">
        @foreach (var item in Model.Dados)
        {
            <tr style="cursor:pointer;" onclick="BuscarAlunos(@item.cidadeid)">
                <td>@(cont = cont + 1)</td>
                <td>@item.cidadeid</td>
                <td>@item.nome</td>
                <td>@item.estado</td>
                <td>@item.cep</td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="10">
                <div class="col-md-4 col-sm-4 col-xs-4 pull-left">
                    @Html.HiddenFor(ent => ent.Paginacao)
                    <span class="link @(Model.Paginacao == 10 ? "link_selecionado" : "")" onclick="mudarPaginacao(5)">5</span>&nbsp;
                </div>
                <div class="col-md-4 col-sm-4 col-xs-4" style="text-align: center;">
                    <div class="form-inline input-group-sm">
                        <button type="button" class="botao botao-primario" onclick="mudarPagina(@(Model.PaginaAtual == 1 ? 1 : Model.PaginaAtual - 1))"><span class="fa fa-chevron-left"></span></button>
                        Página @Html.TextBoxFor(ent => ent.PaginaAtual, new { @class = "form-control", @style = "width: 35px;", @onkeyup = "mudarPagina();" }) de @Model.TotalPaginas &nbsp;
                        <button type="button" class="botao botao-primario" onclick="mudarPagina(@(Model.PaginaAtual == Model.TotalPaginas ? Model.TotalPaginas : Model.PaginaAtual + 1))"><span class="fa fa-chevron-right"></span></button>
                    </div>
                </div>
                <div class="col-md-4 pull-right col-sm-4 col-xs-4" style="text-align: right">
                    <b>Total:</b> @Model.TotalRegistros
                </div>
            </td>
        </tr>
    </tfoot>
</table>