TelaCadastro/ViewModels/CursoViewModel.cs
using DAL.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TelaCadastro.ViewModels
{
    public class CursoViewModel
    {
        public int cursoid { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório!")]
        public string turno { get; set; }
                
        [Required(ErrorMessage = "Campo Obrigatório!")]
        public string descricao { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório!")]
        public int professorid { get; set; }

        public List<SelectListItem> listaturno { get; set; } = new List<SelectListItem>();
        public List<SelectListItem> listaprofessor { get; set; } = new List<SelectListItem>();
    }
}

TelaCadastro/Controllers/CursoController.cs
using DAL.Persistence;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TelaCadastro.ViewModels;

namespace TelaCadastro.Controllers
{
    public class CursoController : Controller
    {
        // GET: Curso
        public CursoDal servico;
        public ProfessorDal servicoProfessor;

        public CursoController()        
        {
            servico = new CursoDal();
            servicoProfessor = new ProfessorDal();
        }

        public ActionResult Index()
        {
            var curso = servico.ObterTodos();
            var listaCurso = new List<CursoViewModel>();

            foreach (var item in curso)
            {
                var itemCurso = new CursoViewModel();

                itemCurso.cursoid = item.cursoid;
                itemCurso.descricao = item.descricao;
                itemCurso.turno = item.turno;

                listaCurso.Add(itemCurso);                
            }
            return View(listaCurso);
        }

        public ActionResult Incluir()
        {
            var listaTurnoSelect = new List<SelectListItem>();

            listaTurnoSelect.Add(new SelectListItem
            {
                Text = "selecione...",
                Value = "",
                Selected = true
            });

            listaTurnoSelect.Add(new SelectListItem
            {
                Text = "Vespertino",
                Value = "V"
            });

            listaTurnoSelect.Add(new SelectListItem
            {
                Text = "Matutino",
                Value = "M"
            });

            var professores = servicoProfessor.ObterTodos().ToList();
            var listaProfessorSelect = new List<SelectListItem>();

            listaProfessorSelect.Add(new SelectListItem
            {
                Text = "Selecione...",
                Value = "",
                Selected = true
            });

            foreach (var prof in professores)
            {
                var selectProfessor = new SelectListItem
                {
                    Text = prof.nome,
                    Value = prof.professorid.ToString()
                };

                listaProfessorSelect.Add(selectProfessor);
            }

            var cursoViewModel = new CursoViewModel();
            cursoViewModel.listaprofessor = listaProfessorSelect;
            cursoViewModel.listaturno = listaTurnoSelect;

            return View(cursoViewModel);
        }
    }   
    
    
}

TelaCadastro/Views/Curso/Index.cshtml
@model List<TelaCadastro.ViewModels.CursoViewModel>
@{
    ViewBag.Title = "Index";
}

<div class="container">
    <div class="painel">
        <div class="row">
            <button type="button" class="botao botao-primario" onclick="window.location.href = '@Url.Action("Incluir", "Curso")'">Criar</button>
        </div>
        <br />
        <div class="row">
            <table id="TabelaCursos">
                <thead>
                    <tr>
                        <th>Código</th>
                        <th>descrição</th>
                        <th>Turno</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var curso in Model)
                    {
                        <tr>
                            <td>@curso.cursoid</td>
                            <td>@curso.descricao</td>
                            <td>@curso.turno</td>
                            <td></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@*O que faz?????*@

@section Scripts{
    <script>
        $(document).ready(function () {
            $("#TabelaCurso").DataTable();
        })
    </script>
}